### ISSUE TITLE
Algorithms numbering

### ISSUE THREAD

**Issue by dppalomar** [SaswatPadhi/pseudocode.js#27]
Thanks for writing pseudocode.js. It looks quite amazing.

By default, pseudocode.js does an automatic numbering starting at 1. I am personally trying to use it in a book, so I need a numbering with the chapters, like Algorithm 2.1 or Algorithm A.1.

I wonder if it would be possible to somehow specify the desired chapter prefix (in the example above it would be prefix "2" or "A").

In the worst case, I wonder if it would be possible to fully specify the number by hand rather than automatic. In the example above, I would specify "2.1" or "A.1".

Thanks!

**Comment by SaswatPadhi** [comment]
Hello @dppalomar,

Sorry about the delay in getting back to you on this issue. I had been away from this project for a while, because of work and family priorities.

I had a chance to think about this today, and a quick solution I could come up with was to allow the options (in particular the `titlePrefix`) to be overridden on a per-element basis, as opposed to it being fixed globally (for all elements).

I pushed a change to implement this idea (see 30f2576509167727ea3ff356ad2635e9df9505ce for the change and examples), so now it should be possible to do something like:

```html
<pre class="pseudocode" data-title-prefix="Algorithm A.">
   ...
</pre>
...
<pre class="pseudocode" data-title-prefix="Algorithm B.">
   ...
</pre>
...
<pre class="pseudocode" data-title-prefix="Algorithm C.">
   ...
</pre>
...
<script>
    pseudocode.renderClass("pseudocode");
</script>
```

Specifying the override on each `<pre>` is repetitive, and I am open to other ideas.

But I am resolving this issue since now there is a way (although a repetitive one) to achieve the desired goal. Thanks again for raising this!
